// <auto-generated />
using System;
using CMMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMMS.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ContractCost")
                        .HasColumnType("float");

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("Equipment ID");

                    b.Property<int>("VenId")
                        .HasColumnType("int")
                        .HasColumnName("Vendor ID");

                    b.HasKey("ContractId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("VenId");

                    b.ToTable("contracts");
                });

            modelBuilder.Entity("CMMS.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DedpartmentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CMMS.Models.Engineer", b =>
                {
                    b.Property<int>("EngId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("Department ID");

                    b.Property<string>("EngEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngFullName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("EngPhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EngId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Engineers");
                });

            modelBuilder.Entity("CMMS.Models.Equipment", b =>
                {
                    b.Property<int>("EqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("Department ID");

                    b.Property<int>("EqCost")
                        .HasColumnType("int");

                    b.Property<string>("EqCurrentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EqInstallatonDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Visiting Time");

                    b.Property<string>("EqName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EqQuantity")
                        .HasColumnType("int");

                    b.Property<int>("EqSerialNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("EqWarrantyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VenId")
                        .HasColumnType("int")
                        .HasColumnName("Vendor ID");

                    b.HasKey("EqId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("VenId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("CMMS.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("Department ID");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("Equipment ID");

                    b.Property<int>("VenId")
                        .HasColumnType("int")
                        .HasColumnName("Vendor ID");

                    b.HasKey("InventoryId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("VenId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("CMMS.Models.Maintenance", b =>
                {
                    b.Property<int>("MaintenaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BreakDownDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BreakDownDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("Department ID");

                    b.Property<int>("DownTime")
                        .HasColumnType("int");

                    b.Property<string>("EngPerformance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EngineerId")
                        .HasColumnType("int")
                        .HasColumnName("Engineer ID");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("Equipment ID");

                    b.Property<DateTime>("MaintenaceDoneOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MaintenaceDueOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecEngRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecUserRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RectCost")
                        .HasColumnType("float");

                    b.Property<DateTime>("RectDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RectDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponseTime")
                        .HasColumnType("int");

                    b.Property<int>("UId")
                        .HasColumnType("int")
                        .HasColumnName("User ID");

                    b.Property<string>("UserRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UsingAfterRectDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VenId")
                        .HasColumnType("int")
                        .HasColumnName("Vendor ID");

                    b.HasKey("MaintenaceId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EngineerId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("UId");

                    b.HasIndex("VenId");

                    b.ToTable("Maintenances");
                });

            modelBuilder.Entity("CMMS.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("Department ID");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UserPhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CMMS.Models.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VendorAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorFullName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("VendorPhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("CMMS.Models.Contract", b =>
                {
                    b.HasOne("CMMS.Models.Equipment", "Equipment")
                        .WithMany("Contracts")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMMS.Models.Vendor", "Vendor")
                        .WithMany("Contracts")
                        .HasForeignKey("VenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CMMS.Models.Engineer", b =>
                {
                    b.HasOne("CMMS.Models.Department", "Department")
                        .WithMany("Engineers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CMMS.Models.Equipment", b =>
                {
                    b.HasOne("CMMS.Models.Department", "Department")
                        .WithMany("Equipments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMMS.Models.Vendor", "Vendor")
                        .WithMany("Equipments")
                        .HasForeignKey("VenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CMMS.Models.Inventory", b =>
                {
                    b.HasOne("CMMS.Models.Department", "Department")
                        .WithMany("Inventories")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMMS.Models.Equipment", "Equipment")
                        .WithMany("Inventories")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMMS.Models.Vendor", "Vendor")
                        .WithMany("Inventories")
                        .HasForeignKey("VenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Equipment");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CMMS.Models.Maintenance", b =>
                {
                    b.HasOne("CMMS.Models.Department", "Department")
                        .WithMany("Maintenances")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMMS.Models.Engineer", "Engineer")
                        .WithMany("Maintenances")
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMMS.Models.Equipment", "Equipment")
                        .WithMany("Maintenances")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMMS.Models.User", "User")
                        .WithMany("Maintenances")
                        .HasForeignKey("UId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMMS.Models.Vendor", "Vendor")
                        .WithMany("Maintenances")
                        .HasForeignKey("VenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Engineer");

                    b.Navigation("Equipment");

                    b.Navigation("User");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CMMS.Models.User", b =>
                {
                    b.HasOne("CMMS.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CMMS.Models.Department", b =>
                {
                    b.Navigation("Engineers");

                    b.Navigation("Equipments");

                    b.Navigation("Inventories");

                    b.Navigation("Maintenances");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CMMS.Models.Engineer", b =>
                {
                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("CMMS.Models.Equipment", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Inventories");

                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("CMMS.Models.User", b =>
                {
                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("CMMS.Models.Vendor", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Equipments");

                    b.Navigation("Inventories");

                    b.Navigation("Maintenances");
                });
#pragma warning restore 612, 618
        }
    }
}
